#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# wallpaper 
nitrogen --restore &

# Polybar
$HOME/.config/polybar/launch.sh &

# Dunst
killall dunst;notify-send BSPWM Restarted &


bspc monitor -d   ﭮ ﱘ    ﴬ   
bspc config border_width        1
bspc config window_gap          15
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config focused_border_color "#928374"


bspc rule -a discord desktop='^3' state=tiling follow=on
bspc rule -a obsidian desktop='^7' state=tiling follow=on
bspc rule -a spotify desktop='^4'
bspc rule -a zathura state=floating
