#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#wallpaper 
nitrogen --restore &

#Polybar
$HOME/.config/polybar/launch.sh

bspc monitor -d   ﭮ ﱘ    ﴬ   

bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focused_border_color "#928374"

bspc rule -a discord desktop='^3' state=tiling follow=on
bspc rule -a obsidian desktop='^7'
bspc rule -a spotify desktop='^4'
bspc rule -a zathura state=tiled
